# Generated by Django 5.2.7 on 2025-11-09 19:06

import django.db.models.deletion
import ehr.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', ehr.fields.ShortUUIDField(editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth_year', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'permissions': [('view_patient_basic', 'Can view basic patient info (non-PHI)'), ('edit_patient_basic', 'Can create/edit basic patient info')],
            },
        ),
        migrations.CreateModel(
            name='PHIDemographics',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ehr.patient')),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('social_security_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'permissions': [('view_phi', 'Can view full PHI (DOB, address, SSN, insurance)'), ('edit_phi', 'Can create/edit PHI records'), ('view_insurance_phi', 'Can view only insurance fields')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', ehr.fields.ShortUUIDField(editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('appointment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('No-Show', 'No-Show')], default='Scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.patient')),
            ],
            options={
                'ordering': ['-appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('admission_id', ehr.fields.ShortUUIDField(editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_date', models.DateTimeField()),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.patient')),
            ],
            options={
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', ehr.fields.ShortUUIDField(editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('staff_type', models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Admin', 'Admin'), ('Billing', 'Billing'), ('Reception', 'Reception'), ('Other', 'Other')], max_length=20)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', ehr.fields.ShortUUIDField(editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.staff')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', ehr.fields.ShortUUIDField(editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('visit_date', models.DateTimeField()),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ehr.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.patient')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ehr.staff')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ehr.staff'),
        ),
        migrations.CreateModel(
            name='AdmissionStaff',
            fields=[
                ('admission_staff_id', ehr.fields.ShortUUIDField(editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('role_in_admission', models.CharField(max_length=50)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.admission')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehr.staff')),
            ],
        ),
        migrations.AddConstraint(
            model_name='admission',
            constraint=models.CheckConstraint(condition=models.Q(('discharge_date__gte', models.F('admission_date')), ('discharge_date__isnull', True), _connector='OR'), name='chk_discharge_date_valid'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='chk_shift_time_valid'),
        ),
        migrations.AlterUniqueTogether(
            name='admissionstaff',
            unique_together={('admission', 'staff')},
        ),
    ]
