# Generated by Django 5.2.7 on 2025-12-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Audit Log Entry', 'verbose_name_plural': 'Audit Log Entries'},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='access_granted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='denial_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tool_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tool_parameters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tool_result_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('TOOL_CALL', 'Tool Call'), ('TOOL_SUCCESS', 'Tool Success'), ('TOOL_FAILURE', 'Tool Failure'), ('ACCESS_GRANTED', 'Access Granted'), ('ACCESS_DENIED', 'Access Denied'), ('PHI_READ', 'PHI Read'), ('PHI_WRITE', 'PHI Write'), ('PHI_DENIED', 'PHI Access Denied'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('SESSION_CREATE', 'Session Created'), ('ERROR', 'System Error'), ('SECURITY_EVENT', 'Security Event')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='record_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['is_phi_access', 'timestamp'], name='audit_audit_is_phi__802b46_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='audit_audit_ip_addr_4a1174_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tool_name', 'timestamp'], name='audit_audit_tool_na_1b91a6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['access_granted'], name='audit_audit_access__b6625b_idx'),
        ),
    ]
